from prometheus_client import Gauge, Counter, Histogram

station_queue_depth = Gauge("station_queue_depth", "Queue depth", ["station"])
station_ready_tracks = Gauge("station_ready_tracks", "Ready tracks", ["station"])
station_buffer_seconds = Gauge("station_buffer_seconds", "Buffered seconds", ["station"])
station_generation_in_progress = Gauge("station_generation_in_progress", "Generation in progress", ["station"])
station_tracks_generated_hourly = Gauge("station_tracks_generated_hourly", "Tracks per hour", ["station"])
station_current_listeners = Gauge("station_current_listeners", "Current listeners", ["station"])
station_peak_listeners_today = Gauge("station_peak_listeners_today", "Peak listeners", ["station"])
station_reuse_rate = Gauge("station_reuse_rate", "Reuse rate", ["station"])
station_repeat_block_count = Counter("station_repeat_block_count", "Repeat blocked", ["station"])
station_failed_generations = Counter("station_failed_generations", "Failed generation", ["station"])
station_qc_rejections = Counter("station_qc_rejections", "QC rejections", ["station"])
station_avg_fit_score = Gauge("station_avg_fit_score", "Avg fit score", ["station"])
station_avg_qc_score = Gauge("station_avg_qc_score", "Avg qc score", ["station"])

generation_jobs_active = Gauge("generation_jobs_active", "Active generation jobs")
generation_jobs_queued = Gauge("generation_jobs_queued", "Queued generation jobs")
generation_latency_seconds = Histogram("generation_latency_seconds", "Latency")
generation_success_total = Counter("generation_success_total", "Generation success")
generation_failure_total = Counter("generation_failure_total", "Generation failures", ["reason"])
generation_retry_total = Counter("generation_retry_total", "Retries")
generation_qc_fail_total = Counter("generation_qc_fail_total", "QC failures")
generation_duplicate_reject_total = Counter("generation_duplicate_reject_total", "Duplicate reject")

storage_hot_bytes = Gauge("storage_hot_bytes", "Hot bytes", ["station"])
storage_warm_bytes = Gauge("storage_warm_bytes", "Warm bytes", ["station"])
storage_cold_bytes = Gauge("storage_cold_bytes", "Cold bytes", ["station"])
storage_temp_bytes = Gauge("storage_temp_bytes", "Temp bytes")
storage_failed_bytes = Gauge("storage_failed_bytes", "Failed bytes")
storage_orphan_files_total = Gauge("storage_orphan_files_total", "Orphan count")
storage_db_file_mismatch_total = Gauge("storage_db_file_mismatch_total", "Mismatch count")
storage_tracks_deleted_total = Counter("storage_tracks_deleted_total", "Deleted tracks")
storage_tracks_promoted_total = Counter("storage_tracks_promoted_total", "Promoted tracks")

listeners_current_total = Gauge("listeners_current_total", "Current listeners")
listeners_current_by_station = Gauge("listeners_current_by_station", "Current listeners by station", ["station"])
listener_sessions_started_total = Counter("listener_sessions_started_total", "Session starts")
listener_disconnects_total = Counter("listener_disconnects_total", "Disconnects")
listener_avg_session_seconds = Gauge("listener_avg_session_seconds", "Avg session")
listener_stream_errors_total = Counter("listener_stream_errors_total", "Stream errors")
listener_skip_events_total = Counter("listener_skip_events_total", "Skip events")
listener_completion_rate = Gauge("listener_completion_rate", "Completion")
listener_rebuffer_events_total = Counter("listener_rebuffer_events_total", "Rebuffer")

tracks_played_new_total = Counter("tracks_played_new_total", "New plays")
tracks_played_reused_total = Counter("tracks_played_reused_total", "Reused plays")
reuse_cooldown_violations_blocked = Counter("reuse_cooldown_violations_blocked", "Cooldown violations blocked")

playback_backend_alive = Gauge("playback_backend_alive", "Playback backend liveness", ["station"])
playback_manifest_age_seconds = Gauge("playback_manifest_age_seconds", "Manifest age", ["station"])
playback_queue_export_age_seconds = Gauge("playback_queue_export_age_seconds", "Queue export age", ["station"])
playback_fallback_active = Gauge("playback_fallback_active", "Fallback active", ["station"])
playback_backend_db_drift_total = Counter("playback_backend_db_drift_total", "Backend/DB drift", ["station"])
